### ISSUE TITLE
Install v0.3.5 fails without `--locked`

### ISSUE THREAD

**Issue by tommilligan** [rust-lang/mdBook#1159]
Very similar to #1124. Installing mdbook with `cargo install --vers '^0.3.5' mdbook` currently fails with:

```log
   Compiling failure_derive v0.1.6
   ...
   <snip>
   ...
error[E0433]: failed to resolve: could not find `__rt` in `quote`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure_derive-0.1.6/src/lib.rs:107:70
    |
107 | fn display_body(s: &synstructure::Structure) -> Result<Option<quote::__rt::TokenStream>, Error> {
    |                                                                      ^^^^ could not find `__rt` in `quote`

error: aborting due to previous error
```

This can be fixed by simply appending `--locked` to the install command.

Would you accept a PR documenting this option in the installation instructions? It's not something I was aware of until my CI failed last night.

**Comment by ehuss** [comment]
> Would you accept a PR documenting this option in the installation instructions?

That would be great!

We should also probably drop `failure` for `anyhow` sometime soon.  I'll try to prioritize some time to look at working on a 0.4 with several breaking changes.
